env:
  commonjs: true
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: 0
  comma-spacing: 2
parserOptions:
  sourceType: "module"
